import type { NextPage } from "next";
import About from "../components/About";
import Gallery from "../components/Gallery";
// import Head from "next/head";
import Page from "../components/Page";
import Experience from "../components/Experience";
import Projects from "../components/Projects";

const Home: NextPage = () => {
  return (
    <Page>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <About />
      <Gallery title="Experience">
        <Experience />
      </Gallery>
      <Gallery title="Projects">
        <Projects />
      </Gallery>
    </Page>
  );
};

export default Home;
