import type { NextPage } from "next";
import About from "../components/About";
import Experience from "../components/Experience";
// import Head from "next/head";
import Page from "../components/Page";

const Home: NextPage = () => {
  return (
    <Page>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <About />
      <Experience />
    </Page>
  );
};

export default Home;
